plugins {
    id 'java'
    id 'war'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'ru.yandex.practicum'
version = 'v1.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
    mavenLocal()
}

dependencies {
    compileOnly 'org.projectlombok:lombok:1.18.36'
    annotationProcessor 'org.projectlombok:lombok:1.18.36'

    // Spring Framework
    implementation 'org.springframework:spring-webmvc:6.1.0'
    implementation 'org.springframework:spring-orm:6.1.0'
    implementation 'org.springframework:spring-context:6.1.0'
    implementation 'org.springframework:spring-test:6.1.0'

    // Database
    implementation 'org.postgresql:postgresql:42.6.0'
    implementation 'com.h2database:h2:2.2.220'
    implementation 'org.hibernate.orm:hibernate-core:6.3.1.Final'
    implementation 'org.springframework.data:spring-data-jpa:3.4.3'

    // JSON
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.15.3'

    // Servlet API
    compileOnly 'jakarta.servlet:jakarta.servlet-api:6.1.0'

    implementation 'org.mapstruct:mapstruct:1.6.3'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.3'

    // Thymeleaf
    implementation 'org.thymeleaf:thymeleaf-spring6:3.1.2.RELEASE'
    implementation 'org.thymeleaf.extras:thymeleaf-extras-springsecurity6:3.1.2.RELEASE'

    // Testing
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.10.0'
    testImplementation 'org.junit.jupiter:junit-jupiter-engine:5.10.0'
    testImplementation 'org.springframework:spring-test:6.1.0'
    testImplementation 'org.mockito:mockito-core:5.5.0'
    testImplementation 'org.hamcrest:hamcrest:2.2'
    testImplementation 'jakarta.servlet:jakarta.servlet-api:6.0.0'
}

tasks.named('test') {
    useJUnitPlatform()
}
