create schema if not exists blog;

create table if not exists blog.post
(
    id              integer generated by default as identity primary key,
    title           varchar,
    body            varchar,
    picture         uuid,
    tags            jsonb,
    created_at      timestamp default now(),
    updated_at      timestamp default now()
);

create table if not exists blog.comment
(
    id              integer generated by default as identity primary key,
    post_id         integer,
    text            varchar,
    author          varchar not null,
    created_at      timestamp default now(),
    updated_at      timestamp default now()
);

create table if not exists blog.tag
(
    id              integer generated by default as identity primary key,
    post_id         integer,
    tag_name        varchar not null,
    created_at      timestamp default now(),
    updated_at      timestamp default now()
);