create schema if not exists blog;

create table if not exists blog.posts
(
    id              integer generated by default as identity primary key,
    title           varchar,
    content         varchar,
    picture         varchar,
    likes           integer,
    created_at      timestamp default now(),
    updated_at      timestamp default now()
    );

create table if not exists blog.comments
(
    id              integer generated by default as identity primary key,
    post_id         integer,
    content         varchar,
    author          varchar not null,
    created_at      timestamp default now(),
    updated_at      timestamp default now()
    );

create table if not exists blog.tags
(
    id              integer generated by default as identity primary key,
    post_id         integer,
    name            varchar not null,
    created_at      timestamp default now(),
    updated_at      timestamp default now()
    );